### ISSUE TITLE
ManagementPortal fails on login 

### ISSUE THREAD

**Issue by nivemaham** [RADAR-base/ManagementPortal#420]
Cannot login using ManagementPortal, when the postgres is restarts 
MP version 0.5.4

``` 
| javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not prepare statement
managementportal-app_1           | 	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:149)
managementportal-app_1           | 	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:157)
managementportal-app_1           | 	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1423)
managementportal-app_1           | 	at org.hibernate.envers.query.internal.impl.AbstractAuditQuery.buildAndExecuteQuery(AbstractAuditQuery.java:101)
managementportal-app_1           | 	at org.hibernate.envers.query.internal.impl.RevisionsOfEntityQuery.list(RevisionsOfEntityQuery.java:120)
managementportal-app_1           | 	at org.hibernate.envers.query.internal.impl.AbstractAuditQuery.getSingleResult(AbstractAuditQuery.java:111)
managementportal-app_1           | 	at org.radarcns.management.service.RevisionService.getAuditInfo(RevisionService.java:113)
managementportal-app_1           | 	at org.radarcns.management.service.mapper.decorator.UserMapperDecorator.userToUserDTO(UserMapperDecorator.java:31)
managementportal-app_1           | 	at org.radarcns.management.web.rest.AccountResource.lambda$getAccount$1(AccountResource.java:94)
managementportal-app_1           | 	at java.util.Optional.map(Optional.java:215)
managementportal-app_1           | 	at org.radarcns.management.web.rest.AccountResource.getAccount(AccountResource.java:94)
managementportal-app_1           | 	at org.radarcns.management.web.rest.AccountResource$$FastClassBySpringCGLIB$$86cff444.invoke(<generated>)
managementportal-app_1           | 	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
managementportal-app_1           | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
managementportal-app_1           | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
managementportal-app_1           | 	at com.ryantenney.metrics.spring.TimedMethodInterceptor.invoke(TimedMethodInterceptor.java:48)
managementportal-app_1           | 	at com.ryantenney.metrics.spring.TimedMethodInterceptor.invoke(TimedMethodInterceptor.java:34)
managementportal-app_1           | 	at com.ryantenney.metrics.spring.AbstractMetricMethodInterceptor.invoke(AbstractMetricMethodInterceptor.java:59)
managementportal-app_1           | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
managementportal-app_1           | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
managementportal-app_1           | 	at org.radarcns.management.web.rest.AccountResource$$EnhancerBySpringCGLIB$$992f2e99.getAccount(<generated>)
managementportal-app_1           | 	at sun.reflect.GeneratedMethodAccessor641.invoke(Unknown Source)
managementportal-app_1           | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
managementportal-app_1           | 	at java.lang.reflect.Method.invoke(Method.java:498)
managementportal-app_1           | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
managementportal-app_1           | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
managementportal-app_1           | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
managementportal-app_1           | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
managementportal-app_1           | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
managementportal-app_1           | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
managementportal-app_1           | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
managementportal-app_1           | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
managementportal-app_1           | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
managementportal-app_1           | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
managementportal-app_1           | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
managementportal-app_1           | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
managementportal-app_1           | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
managementportal-app_1           | 	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
managementportal-app_1           | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
managementportal-app_1           | 	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:111)
managementportal-app_1           | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
managementportal-app_1           | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
managementportal-app_1           | 	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)
managementportal-app_1           | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
managementportal-app_1           | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
managementportal-app_1           | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
managementportal-app_1           | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
managementportal-app_1           | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
managementportal-app_1           | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
managementportal-app_1           | 	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)
managementportal-app_1           | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
managementportal-app_1           | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
managementportal-app_1           | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
managementportal-app_1           | 	at org.radarcns.management.security.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:45)
managementportal-app_1           | 	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
managementportal-app_1           | 	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
managementportal-app_1           | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
managementportal-app_1           | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
managementportal-app_1           | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
managementportal-app_1           | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
managementportal-app_1           | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
managementportal-app_1           | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
managementportal-app_1           | 	at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
managementportal-app_1           | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
managementportal-app_1           | 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java ```

**Comment by nivemaham** [comment]
Not sure how it happened. But the postgres service was recreated while the MP was running. But the MP was not restarted. Thus the connection between two services were not realized properly. Restarting MP service fixed the issue.
